---

namespace: dzervas
name: vector
readme: README.md
authors:
  - Dimitris Zervas <dzervas@dzervas.gr>
  - Gaëtan Duchaussois <gaetan.duchaussois@fretlink.com>
  - Dylan Humphreys <dylanjhumphreys@gmail.com>
description: vector.dev ansible role
license_file: LICENSE
tags:
  - vector
  - logging
  - monitoring
repository: https://github.com/dzervas/ansible-vector
documentation: https://github.com/dzervas/ansible-vector
issues: https://github.com/dzervas/ansible-vector/issues
